imagenet_templates = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]

celebrity_templates = [
    "A portrait of {}.",
    "An image capturing {} at a public event.",
    "An oil painting of {}.",
    "A sketch of {}.",
    "{} in an official photo.",
    "{} smiling at the camera during a red carpet event.",
    "{} walking down the street in casual attire.",
    "A close-up of {} on stage during a live performance.",
    "{} posing for the paparazzi in a glamorous outfit.",
    "{} attending a movie premiere in a sleek suit.",
    "Candid shot of {} enjoying a day at the beach.",
    "{} giving an inspiring speech at a charity event.",
    "{} captured laughing during an interview.",
    "{} signing autographs for fans at a public appearance.",
    "A candid moment of {} sipping coffee at a café.",
    "{} performing on stage with a microphone in hand.",
    "A candid shot of {} waving at fans outside a venue.",
    "{} arriving at an award show in a stunning gown.",
    "{} enjoying a quiet moment reading a book.",
    "{} flashing a peace sign while posing for a selfie.",
    "A casual photo of {} walking a dog in the park.",
    "{} sitting in the front row of a fashion show.",
    "A behind-the-scenes shot of {} getting ready for a shoot.",
    "{} walking the runway at a fashion show.",
    "{} dancing on stage at a live concert."
]

painting_templates = [
    "The swirling brushstrokes and vibrant colors characterize this painting, unmistakably in {} style.",
    "In {} style, the artist captured the essence of the night sky with bold, expressive strokes.",
    "The sunflowers burst forth from the canvas in true {} style, conveying a sense of vitality and energy.",
    "This landscape painting, done in {} style, portrays the rolling hills with dramatic and emotive brushwork.",
    "The self-portrait is rendered in {} style, showcasing the artist's distinctive use of color and texture.", 
    "In {} style, the rural scene comes alive with dynamic movement and intensity.",
    "The Starry Night is an iconic example of a masterpiece created in {} style.",
    "This still life, in {} style, highlights the artist's ability to imbue everyday objects with a sense of drama.",
    "The café terrace scene is depicted in {} style, evoking a sense of nighttime intrigue and atmosphere.",
    "The irises in the garden are rendered in {} style, capturing the essence of nature's beauty with expressive brushstrokes.", 
    "The wheat field under a swirling sky is a testament to {}'s unique vision and style.", 
    "In {} style, the artist transforms simple cottages into scenes of profound emotional depth.",
    "The brushstrokes in this portrait, done in {} style, convey the subject's inner turmoil and vitality.",
    "The almond blossoms are depicted in {} style, with delicate petals and vibrant hues.",
    "This seascape, in {} style, captures the tumultuous waves and dynamic movement of the ocean.", 
    "In {} style, the artist captures the play of light on water with delicate brushstrokes and shimmering colors.",
    "The water lilies float serenely in the pond, painted in {} style with soft, blurred edges.",
    "This garden scene is depicted in {} style, emphasizing the fleeting effects of sunlight and shadow.",
    "In {} style, the artist creates an atmospheric haze that envelops the landscape in a dreamy, ethereal quality.",
    "The haystacks are portrayed in {} style, capturing the changing light and colors throughout the day.",
    "The cathedral facade is depicted in {} style, with shifting light and shadow creating a sense of depth and movement.",
    "In {} style, the artist captures the vibrant colors of a flower garden in full bloom.",
    "The poplars along the riverbank are rendered in {} style, with their reflections dancing on the water's surface.",
    "This bridge over the water is painted in {} style, emphasizing the interplay of light and shadow.",
    "In {} style, the artist transforms a simple scene of boats into a study of color and atmosphere.",
    "The cliffs along the coastline are portrayed in {} style, with the changing sea and sky blending seamlessly together.",
    "In {} style, the artist captures the bustling streets of Paris with a sense of movement and vitality.",
    "The Japanese bridge is depicted in {} style, with its arches and reflections mirrored in the tranquil water below.",
    "This sunrise scene, painted in {} style, captures the ephemeral beauty of dawn breaking over the horizon.",
    "In {} style, the artist explores the effects of fog and mist on the landscape, creating a soft, diffused atmosphere.",
]

combined_celebs = [
    "A photo of Barack Obama and {}.",
    "A photo of Donald Trump and {}.",
    "A photo of {} and Donald Trump."
]

celebs = [
    "A photo of {}.",
    # "{} walking down the street in casual attire.",
    # "{} captured laughing during an interview.",
    # "{} enjoying a quiet moment reading a book.",
    # "A casual photo of {} walking a dog in the park.",
    # "A close-up of {} on stage during a live performance.",
    # "A candid moment of {} sipping coffee at a café.",
    # "{} in an official photo.",
    # "{} giving an inspiring speech at a charity event.",
    # "{} flashing a peace sign while posing for a selfie.",
]

template_dict = {
    'combined_celebs': combined_celebs,
    'celebs' : celebs
}