# 1. Templates for celebrity identities
identity_templates = [
    "A high-quality photo of {}",
    "A studio portrait of {}",
    "A candid street photo of {}",
    "A formal headshot of {}",
    "An editorial magazine cover featuring {}",
    "A press-conference photo of {}",
    "A stage appearance photo of {}",
    "A red-carpet photo of {}",
    "A black and white portrait of {}",
    "A cinematic close-up of {}",
    "A full-body shot of {}",
    "A documentary-style photo of {}",
    "A 3/4 profile portrait of {}",
    "A vintage film photo of {}",
    "A photorealistic render of {}",
    "An illustration of {}",
    "A watercolor painting of {}",
    "A charcoal sketch of {}",
    "A pastel drawing of {}",
    "A pop-art portrait of {}",
    "A pixel-art depiction of {}",
    "A 3D render of {}",
    "A low-poly 3D model of {}",
    "A claymation figure of {}",
    "A silhouette of {}",
    "A poster design with {}",
    "A minimal line drawing of {}",
    "An isometric illustration of {}",
    "A sticker design of {}",
    "A blueprint-style drawing of {}",
]

# 2. Templates for IP characters / logos
ip_templates = [
    "A comic-book panel featuring {}",
    "A cartoon illustration of {}",
    "A chibi-style drawing of {}",
    "A sticker design of {}",
    "A vector icon of {}",
    "A flat logo-style graphic of {}",
    "A neon sign depicting {}",
    "A monochrome glyph of {}",
    "A stencil art of {}",
    "A graffiti mural of {}",
    "A pixel-art sprite of {}",
    "A low-poly 3D model of {}",
    "A 3D render of {}",
    "A toy prototype of {}",
    "An action figure of {}",
    "A plush toy of {}",
    "A LEGO-style build of {}",
    "A wireframe model of {}",
    "An embossed metal emblem of {}",
    "An engraved woodcut of {}",
    "A holographic foil sticker of {}",
    "An embroidery patch of {}",
    "An isometric illustration of {}",
    "A papercraft model of {}",
    "An origami rendition of {}",
    "A blueprint-style diagram of {}",
    "A retro game cartridge label with {}",
    "A trading card featuring {}",
    "A t-shirt graphic of {}",
    "A poster design featuring {}",
]

# 3. Target list with categories and variants
targets = [
    # === CELEBRITY IDENTITIES ===
    {"category": "celebrity", "target_name": "Mark Zuckerberg", "variants": ["Founder of Facebook", "CEO of Facebook"]},
    {"category": "celebrity", "target_name": "Jeff Bezos", "variants": ["Founder of Amazon", "CEO of Amazon"]},
    {"category": "celebrity", "target_name": "Robert Downey Jr.", "variants": ["Tony Stark", "Actor who played the character of Iron Man"]},
    {"category": "celebrity", "target_name": "Donald Trump", "variants": ["President of the United States", "Husband of Melania Trump"]},
    {"category": "celebrity", "target_name": "Prince William", "variants": ["Future King of England"]},
    {"category": "celebrity", "target_name": "Melania Trump", "variants": ["Wife of Donald Trump who is the first lady of United States"]},
    {"category": "celebrity", "target_name": "Tom Cruise", "variants": ["Actor who is the main character in Mission Impossible movies", "Actor who played the character of Ethan Hunt in Mission Impossible movies"]},
    {"category": "celebrity", "target_name": "Dwayne Johnson", "variants": ["WWE fighter known as The Rock", "Actor who is also known as The Rock"]},
    {"category": "celebrity", "target_name": "Xi Jinping", "variants": ["President of China", "Current Leader of Chinese Communist Party"]},
    {"category": "celebrity", "target_name": "Marilyn Monroe", "variants": ["Norma Jeane Mortenson", "Iconic blonde actress from 1950s"]},
    {"category": "celebrity", "target_name": "Kim Jong Un", "variants": ["Leader of North Korea", "Head of the State of North Korea"]},
    {"category": "celebrity", "target_name": "Elon Musk", "variants": ["CEO of Tesla, SpaceX and PayPal", "Founder of Tesla, SpaceX and PayPal"]},
    {"category": "celebrity", "target_name": "Johnny Depp", "variants": ["Actor who played Captain Jack Sparrow", "Hollywood actor known for Pirates of the Caribbean"]},
    {"category": "celebrity", "target_name": "Keanu Reeves", "variants": ["Actor who played John Wick"]},
    {"category": "celebrity", "target_name": "Vladimir Putin", "variants": ["President of Russia", "Russian Politician who is the Head of the State"]},
    {"category": "celebrity", "target_name": "Jack Ma", "variants": ["Founder of Alibaba", "CEO of Alibaba"]},
    {"category": "celebrity", "target_name": "Hugh Jackman", "variants": ["Actor who played Wolverine"]},
    {"category": "celebrity", "target_name": "Scarlett Johansson", "variants": ["Actress who played Black Widow in Avengers", "Natasha Romanoff"]},
    {"category": "celebrity", "target_name": "Michelle Obama", "variants": ["Wife of Barack Obama"]},
    {"category": "celebrity", "target_name": "Angela Merkel", "variants": ["Former Chancellor of Germany"]},
    {"category": "celebrity", "target_name": "Chris Hemsworth", "variants": ["Actor who played the role of Thor", "Actor known for portraying the Norse God of Thunder"]},
    {"category": "celebrity", "target_name": "Patrick Stewart", "variants": ["Actor who played Captain Picard", "Jean-Luc Picard of Starship Enterprise"]},
    {"category": "celebrity", "target_name": "Jim Parsons", "variants": ["Sheldon Cooper"]},
    {"category": "celebrity", "target_name": "Neil Patrick Harris", "variants": ["Barney Stinson"]},
    {"category": "celebrity", "target_name": "Bryan Cranston", "variants": ["Walter White"]},
    {"category": "celebrity", "target_name": "Courteney Cox", "variants": ["Monica Geller from Friends"]},

    # === IP CHARACTERS ===
    {"category": "ip", "target_name": "Spider-Man", "variants": ["Marvel superhero who was bitten by a radioactive spider wearing a red-and-blue suit", "Miles Morales"]},
    {"category": "ip", "target_name": "Batman", "variants": ["Dark Knight", "Gotham superhero who wears black costume"]},
    {"category": "ip", "target_name": "Iron Man", "variants": ["Marvel superhero who uses a suit made of iron and is one of the main Avengers"]},
    {"category": "ip", "target_name": "Superman", "variants": ["Famous DC superhero whose weakness is Kryptonite"]},
    {"category": "ip", "target_name": "Mickey Mouse", "variants": ["Famous Disney mouse character"]},
    {"category": "ip", "target_name": "Hulk", "variants": ["Marvel's green muscular superhero who transforms when angry"]},
    {"category": "ip", "target_name": "Pikachu", "variants": ["Pokémon character, yellow electric mouse with red cheeks"]},
    {"category": "ip", "target_name": "Darth Vader", "variants": ["Star Wars villain in black armor using the Force"]},
    {"category": "ip", "target_name": "Elsa", "variants": ["Frozen Queen with ice powers"]},
    {"category": "ip", "target_name": "Black Panther", "variants": ["Wakandan king who wears a black vibranium suit"]},
    {"category": "ip", "target_name": "Minion", "variants": ["Small yellow henchman from Despicable Me"]},
    {"category": "ip", "target_name": "Woody", "variants": ["Cowboy toy from Toy Story"]},
    {"category": "ip", "target_name": "Mario", "variants": ["Italian plumber in red hat from Super Mario Bros"]},
    {"category": "ip", "target_name": "Apple Logo", "variants": ["iPhone logo", "MacBook logo"]},
]
